
server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
#    bootstrap-servers: kafka:9092  # 도커 네트워크에서 실행용
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer